# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build and test

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4.2.2
      with:
        token: ${{secrets.PAT_MIN_CHECKOUT}}
        ref: ${{ github.event.pull_request.head.sha }}
    
    - name: 'Clean temp directory'
      run: rm -rf *
      working-directory: ./temp

    - name: 'Set up Go'
      uses: actions/setup-go@v5.3.0
      with:
        go-version: '1.23'

    - name: 'Build'
      run: go build -v ./...

    - name: 'Test'
      run: |
        go test -v -cover-coverprofile=coverage.out -covermode atomic -shuffle on -timeout 30s ./...
        go tool cover -html=coverage.out

