# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build and test

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4.2.2
      with:
        token: ${{secrets.PAT_MIN_CHECKOUT}}
        ref: ${{ github.event.pull_request.head.sha }}

      #    - name: 'Clean temp directory'
      #      run: rm -rf *
      #      working-directory: ~/temp

    - name: 'Set up Go'
      uses: actions/setup-go@v5.3.0
      with:
        go-version: '1.23'

    - name: 'Build'
      run: go build -v ./...

    - name: 'Test'
      run: |
        go test -v ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./... -shuffle=on -timeout=30s

    - name: 'Check test coverage'
      uses: vladopajic/go-test-coverage@v2
      with:
        config: ./.testcoverage.yml

    - name: 'Coverage HTML report'
      run: go tool cover -html=cover.out -o=cover.html